server:
  port: 9002

spring:
  application:
    name: configuration-service
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configs
#        git:
#          uri: file://${user.home}/application-config

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
