spring:
  application:
    name: api-gateway-service
  config:
    import: "configserver:"
  cloud:
    config:
      name: api-gateway
      uri: http://localhost:9002

  data:
    redis:
      host: localhost
      port: 6379