logging:
  level:
    root: INFO

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0

zipkin:
  base-url: http://zipkin:9411